#server:
#  port: 8080
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: "jdbc:mysql://localhost:3306/session1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8"
#    username: "root"
#    password: "123456"
#mybatis:
#  mapper-locations: "classpath:mapper/*.xml"
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl